name: Dependabot Automerge
on:
  pull_request_target:
    types: [opened, reopened, synchronize]
jobs:
  merge:
    uses: rubykatzen/baseline/.github/workflows/dependabot-automerge.yml@v0.0.12
    secrets: inherit
