name: Lint
on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: rubykatzen/baseline/.github/actions/lint-yamllint@v0.7
      - uses: rubykatzen/baseline/.github/actions/lint-ruff@v0.7
      - uses: rubykatzen/baseline/.github/actions/lint-actionlint@v0.7
