name: Merge Dependabot PR
on:
  pull_request_target:
    types: [opened, reopened, synchronize]
jobs:
  merge:
    uses: ./.github/workflows/merge-dependabot-pr-shared.yml
    with:
      max-update-type: minor
    secrets: inherit
