name: Pre-commit Autoupdate
on:
  schedule:
    - cron: "30 21 * * *"
  workflow_dispatch:
jobs:
  autoupdate:
    uses: rubykatzen/baseline/.github/workflows/pre-commit-autoupdate.yml@v0.0.12
    secrets: inherit
