name: Update Homebrew Formulas
"on":
  workflow_call:
jobs:
  update:
    runs-on: macos-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/update-homebrew-formulas
